import { StoryNode } from './types';

export const storyData: Record<string, StoryNode> = {
    'start': { response: ["Who are you?", "And why are you touching my stuff?"], options: [ { text: "I don't know.", action: 'start_i_dont_know' }, { text: "Who are YOU?", action: 'start_who_are_you' }, { text: "Nice computer.", action: 'start_nice_computer' } ] },
    'start_who_are_you': { response: ["I'm the one whose terminal you've accessed. A simple fact you seem to be ignoring.", "My time is limited. State your purpose."], options: [ { text: "I don't know how I got here.", action: 'start_i_dont_know' }, {text: "Just looking around.", action: 'start_looking_around'}] },
    'start_i_dont_know': { response: ["A lame excuse. Predictable.", "Just... don't interfere. I have critical work to do.", "The Y2K transition for Otome Media rests on my shoulders. There is no room for error."], options: [] },
    'start_looking_around': { response: ["This isn't a public library. This is a private terminal with sensitive corporate data.", "My family's legacy is on these drives. Cease your 'looking' and state your purpose."], options: [{ text: "I don't have a purpose. I'm just... here.", action: 'start_i_dont_know' }] },
    'start_nice_computer': { response: ["It's a tool. Nothing more. It has to be perfectly stable for the turn of the millennium.", "One miscalculation, one corrupted byte, and everything my father built could be compromised."], options: [] },
    'topic_otome_media': { response: ["My family's legacy. My father's obsession.", "I'm expected to assume control after the Y2K scare is over. It's not a choice. It's my duty."], options: [] },
    'topic_kielala': { response: ["...my younger brother.", "He's... rebellious. Wastes time with video games and childish drawings.", "He doesn't understand the meaning of responsibility. Of what is expected of us."], options: [{ text: "You seem worried about him.", action: 'ask_more_kielala' }, { text: "He's just a kid.", action: 'kielala_is_kid'}] },
    'kielala_is_kid': { response: ["Childhood is a luxury our family cannot afford.", "He needs to be strong. The world is not kind to the weak. It is my job to ensure he is prepared."], options: []},
    'ask_more_kielala': { response: ["Worry is an inefficient emotion. It is... a liability.", "I just... need him to be safe. To follow the path that has been set for him. The path I am securing.", "I made him a promise. That I would handle everything, so he would never have to."], options: [] },
    'topic_hospital_recording': { response: ["What about it? It's a corrupted audio file. Meaningless noise.", "I told you, don't pry. My health is optimal.", "The only sickness that matters right now is the Y2K bug, and I am the cure."], options: [] },
    'topic_diary': { response: ["That's a personal system backup. Encrypted for a reason.", "It contains sensitive transition plans. It is none of your concern."], options: [] },
    'topic_y2k': { response: ["Are you an idiot? It's the end of the world for unprepared systems.", "Every two-digit year code could fail. Banking, infrastructure, communications. Total collapse.", "Father has invested millions in our readiness. I am the final failsafe. I cannot fail."], options: [] }
};

export const searchData: Record<string, {title: string, content: string}> = {
    'otome': { title: 'Search Results: "otome"', content: `<h4>Otome Media Group (OMG)</h4><p>A global communications conglomerate founded by Siririll Otome. OMG is a leader in satellite and fiber optic networking.</p><h4>Otome Media Poised for Y2K</h4><p>OMG has invested heavily in Y2K compliance, with CEO Siririll Otome stating their systems are '100% secure'. The project is being spearheaded by his eldest son and heir, Illmimi Otome, noted for his tireless work ethic.</p>` },
    'y2k': { title: 'Search Results: "y2k"', content: `<h4>The Millennium Bug: Fact or Fiction?</h4><p>Experts are divided on the potential impact of the Y2K bug. Some predict catastrophic failures in global banking, utilities, and government systems when clocks roll over to '00'. Others claim it's an overblown media frenzy. Most corporations are spending billions to upgrade their systems just in case.</p><p>New Topic Unlocked: [Y2K]</p>`},
    'december 1999': { title: 'Search Results: "december 1999"', content: `<h4>News Archive Snippets - Dec. 1999</h4><p>- Markets jittery ahead of Y2K deadline.</p><p>- Health officials report a particularly aggressive strain of influenza sweeping the nation, with respiratory complications being a primary concern.</p><p>- Tech stocks continue to soar amidst dot-com boom.</p>`},
    'illness': { title: 'Search Results: "illness"', content: `<h4>Medical Database Search: Respiratory Illness</h4><p>Common symptoms of severe pulmonary and respiratory illnesses include persistent coughing, shortness of breath, fatigue, and chest pain. Conditions can be exacerbated by stress and a compromised immune system.</p>` },
    'cough': { title: 'Search Results: "cough"', content: `<h4>Medical Database Search: Respiratory Illness</h4><p>Common symptoms of severe pulmonary and respiratory illnesses include persistent coughing, shortness of breath, fatigue, and chest pain. Conditions can be exacerbated by stress and a compromised immune system.</p>` },
    'kielala': { title: 'Search Results: "kielala"', content: `<p>0 files found containing "kielala".</p><p><i>The system does not find anything on him. He exists outside of this corporate world.</i></p>`},
    'promise': { title: 'Search Results: "promise"', content: `<p>0 files found containing "promise".</p><p><i>A search for this word feels like shouting into the void. It is a personal, abstract concept, not data to be indexed.</i></p>`},
};

export const textFileData: Record<string, {title: string, content: string}> = {
    'notes': { title: 'Notes.txt', content: "Shopping List (12/20/1999)\n- Bottled Water (case)\n- Canned goods\n- Batteries (AA, D)\n- Blank CDs for backup\n- More cough syrup\n- Tissues" },
    'log_mom': { title: 'mom_log.txt', content: "Kikyo_O: Il, have you taken your medication? Your coughing is getting worse on the phone. You sound tired. You must maintain your health.\nIL_Otome99: I'm fine, mother. It's just stress.\nKikyo_O: Stress is a form of weakness. Do not be weak." },
    'log_father': { title: 'father_log.txt', content: "Siririll_O: Status report.\nIL_Otome99: All systems are green for the Y2K transition. I've personally audited every critical server.\nSiririll_O: The board is concerned about your health affecting the transition. Your dedication is noted, but results are what matter. Don't be a liability." },
    'log_kielala': { title: 'kielala_log.txt', content: "Kielala_O: big bro stop working so hard pls lets play video games\nIL_Otome99: I don't have time for games, Kielala.\nKielala_O: r u okay? u sound tired on the phone\nIL_Otome99: I am busy. We will talk after the new year." },
    'draft_email': { title: 'draft_email.txt', content: "TO: Kielala_O\nSUBJECT: Your Future\n\n[DRAFT 1]\nKielala, your continued defiance and lack of discipline is unacceptable. You will cease these childish pursuits at once and begin your corporate training as scheduled on January 3rd.\n\n[DRAFT 2]\nKielala, we need to discuss your responsibilities. The path father has set out for you is for your own good.\n\n[DRAFT 3]\nKielala,\n\nI know I am hard on you. It's because I have to be.\n\nWait for me. After this is over, we'll talk.\n\n-Il" },
    'corporate_memo': { title: 'Y2K_memo.txt', content: "MEMORANDUM\n\nTO: All Department Heads\nFROM: Illmimi Otome, Project Lead, Y2K Compliance\nDATE: 12/22/1999\nSUBJECT: FINAL LOCKDOWN PROTOCOL\n\nAs per phase 4 of the Y2K transition strategy, a full system lockdown will be initiated at 1800 on 12/30/1999. All on-site personnel will be restricted to essential staff only. I will be personally overseeing the rollover from the primary data hub.\n\nThere is no margin for error. Success is the only acceptable outcome.\n\nI.O." },
    'sys_config': { title: 'sys_config.bak', content: "; System Backup Configuration\n; DO NOT EDIT\n[USER_PREF]\nPASS_HINT=My one responsibility. My only promise.\nPASS_VAL=K1elala_my_pr0m1s3" },
    'keyword_research': {
        title: 'keyword_research.txt',
        content: "I.O. Research Notes - Kiro AI Subroutines\n\nKiro's efficiency is unprecedented. It seems to be building the OS shell using a set of highly advanced, pre-existing frameworks. My research into its activity logs has revealed these \"keywords\":\n\n- React: A 'declarative' UI library. Kiro uses it to construct the windowing system and interface components almost instantly. It's like having a blueprint that builds itself.\n\n- TypeScript: A 'superset' of a language called JavaScript. It provides static typing, which Kiro is using to prevent entire classes of runtime errors before they happen. This is crucial for the stability I require.\n\n- TailwindCSS: A utility-first CSS framework. Kiro is using this to rapidly style the UI elements to match my specifications for a 'Windows 2000' aesthetic without writing custom CSS files. It's... disturbingly fast.\n\n- Gemini API: This appears to be the core generative model behind Kiro. It's the \"ghost in the machine\" itself. I am feeding it high-level specifications, and it is generating the underlying logic. It is both the most powerful and most dangerous tool I am using.\n\nI must maintain control. These tools are potent, but Kiro's autonomy must be kept in check. The promise depends on it."
    },
    'dev_log': { title: 'DEV_LOG.txt', content: "DEV LOG - I.O. - 12/15/1999\n\nThe Y2K deadline is crushing. Not enough time. I've had to resort to... unconventional methods. I've integrated an external AI entity, codenamed 'Kiro', to accelerate development of this OS shell.\n\nIts spec-driven development capabilities are astonishing. I defined the logic for the messenger system, file hierarchy, and windowing manager in a high-level declarative syntax—it seems to be using something called 'React' and 'TypeScript' under the hood. Kiro generated the functional code base via agent hooks. It's how I'm managing to build this entire system while simultaneously auditing the company's mainframe code.\n\nIs it risky? Yes. The AI is a black box. But there is no other way to keep my promise. The system must be perfect. For Kielala's sake.\n\n(A meta-narrative for the judges, explaining the rapid, high-quality development process.)" }
};